services:
  madax-page:
    container_name: madax-page
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - proxy_network
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    mem_limit: 100m
    cpus: 0.5

networks:
  proxy_network:
    external: true
